#!/usr/bin/python2

"""
Reads json files generated by hadouken.py and populate the sqlite3 database, it was testedon RHEL 5/6 and 7 with python
2.x.
"""

import os
import shutil
import sqlite3
import json

project_dir = '/appl/hadouken'
my_project = '/home/diegorsantos/PycharmProjects/hadouken'
for each in os.listdir('%s/json/' % my_project):
    if each.endswith('.json'):
        os.chdir(r'%s/json/' % my_project)
        with open(each) as fp:
            try:
                hadouken = json.load(fp)
                db = sqlite3.connect('%s/db/db.sqlite' % my_project)
                cursor = db.cursor()
                cursor.execute(
                    'INSERT OR IGNORE INTO info(server_name,server_release,server_site,server_vendor,server_model,'
                    'server_serial,server_cpu,server_memory,server_ip,server_cluster,server_clusternodes,server_frame,'
                    'server_wwpn,server_db) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)',
                    (
                        hadouken['server_name'], hadouken['server_release'], hadouken['server_site'],
                        hadouken['server_vendor'],
                        hadouken['server_model'], hadouken['server_serial'], hadouken['server_cpu'],
                        hadouken['server_memory'],
                        hadouken['server_ip'], hadouken['server_cluster'], hadouken['server_clusternodes'],
                        hadouken['server_frame'], hadouken['server_wwpn'], hadouken['server_db']))
                db.commit()
                db.close()

                infile = '%s/json/%s' % (my_project, each)
                outfile = '%s/tmp/%s' % (my_project, each)
                shutil.move(infile, outfile)

            except ValueError as e:
                continue
