#!/usr/bin/python

'''
Easily collect the json files generated by hadouken.py from all hosts from your environment, it was tested on RHEL 5/6
and 7 with python 2.x.
'''

import platform
import subprocess

# checks if operating system is Linux.
if platform.system() == 'Linux':
    # call ansible-playbook
    proc = subprocess.Popen(
        ["/usr/bin/ansible-playbook -i /appl/hadouken/conf/hosts /appl/hadouken/conf/task.yml"],
        stdout=subprocess.PIPE, shell=True)
    x = proc.communicate()[0]

    # call hadoukendb.py to populate the sqlite3 db.
    proc = subprocess.Popen(
        ["/appl/hadouken/sbin/db.py"],
        stdout=subprocess.PIPE, shell=True)
    x = proc.communicate()[0]
